# Generated by Django 5.1.1 on 2026-04-18 11:13

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, help_text='Короткая ссылка на рецепт', max_length=64, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Количество ингредиента', validators=[api.validators.validate_positive_number], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления рецепта', validators=[api.validators.validate_positive_number], verbose_name='Время приготовления'),
        ),
    ]
