# Generated by Django 5.1.1 on 2026-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
