# Generated by Django 5.1.1 on 2026-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, help_text='Короткая ссылка для получения рецепта', max_length=128, null=True, verbose_name='Короткая ссылка'),
        ),
    ]
