# Generated by Django 5.1.1 on 2026-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, help_text='Короткая ссылка для получения рецепта', max_length=128, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
