# Generated by Django 5.1.1 on 2026-04-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_url',
        ),
    ]
