# Generated by Django 5.1.1 on 2026-04-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_remove_recipe_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure_unit',
            new_name='measurement_unit',
        ),
    ]
