# Generated by Django 5.1.1 on 2026-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='Пароль пользователя', max_length=256, verbose_name='Пароль'),
        ),
    ]
