# Generated by Django 5.1.1 on 2026-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
